<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category Name_categoryName</name>
   <tag></tag>
   <elementGuidId>7d621619-3ff6-4979-b41c-bbd8bfc0ce37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f70ed8f-5470-465c-9710-f790648daaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09bd7a08-ad90-400c-b9f8-e29b0c6ed969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae3f8ba4-d1ce-4c44-8053-c7094d9cc9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>cb2c25e9-7748-46ac-abe8-d32da43eb602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categoryName</value>
      <webElementGuid>55c10119-df85-43c8-add7-303dcaef7b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_name&quot;)</value>
      <webElementGuid>472b85b2-fbf3-435b-a961-4398cebf5219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_name']</value>
      <webElementGuid>53fe865e-8672-4aab-8306-85c851a19aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8e60b736-80bc-4f6b-89cb-ea61d3cebeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'category_name' and @name = 'categoryName']</value>
      <webElementGuid>f19e1599-d89c-4bef-895e-5bc0e04e64e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
