<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of pages_pages</name>
   <tag></tag>
   <elementGuidId>fd0245b5-d049-4b1a-8cdd-4a240ac6371a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pages</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pages']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>164ed73b-21da-4c8b-916e-1d99c428f696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c37c048-479c-4b60-92a6-7094391d5cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>97f2a283-0a23-4eb4-81cb-e68693d410c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pages</value>
      <webElementGuid>7080027c-e308-4f6e-b358-c06292e749ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pages</value>
      <webElementGuid>e6ff5db4-d566-42a8-828e-93ffac555185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pages&quot;)</value>
      <webElementGuid>0643ac88-e5e9-4a65-b722-80fb3c6ae613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pages']</value>
      <webElementGuid>a56b9a93-f4bc-428d-9dab-623259cbf0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/input</value>
      <webElementGuid>684b199a-5f1f-4142-b0bd-93691d4b14b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pages' and @name = 'pages']</value>
      <webElementGuid>14803d11-125a-48c6-98be-b6876b194c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
