<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Author_author_name</name>
   <tag></tag>
   <elementGuidId>8589ed41-3270-4516-8314-10b8a31eb01d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#author_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='author_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65b49805-ad2a-454e-991f-f90e2cfd2712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c47f4b0-2f25-4ab7-b36e-9c74e8a3ca77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>baaa5903-7a49-4ed5-a631-71833ee081e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>author_name</value>
      <webElementGuid>6ec05a6e-4941-4a89-842f-c2f090489795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>author_name</value>
      <webElementGuid>b998048e-2554-43d1-8dc1-93fa0b439af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;author_name&quot;)</value>
      <webElementGuid>8f2b63ee-7d30-4a1b-a7ee-8aaeb95b5e62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='author_name']</value>
      <webElementGuid>f4bfaa36-ae4e-463f-b424-bd0aba0fcf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>2a600145-ea4b-46ca-ab34-88c40801c16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'author_name' and @name = 'author_name']</value>
      <webElementGuid>a29984b4-5c03-4e74-9956-a917357fb01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
