<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Publisher_publisher</name>
   <tag></tag>
   <elementGuidId>4946e2d0-e6a6-4883-959c-511bd4df9195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#publisher</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='publisher']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85c22df8-418c-412c-afdd-4d47a84a3a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bf62d0c-27bb-406f-b618-a25511546fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aaa25d62-08b7-40e1-801e-b83fc07d39e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>publisher</value>
      <webElementGuid>41fc4133-0227-4cbf-94e3-2260f1ed21eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>publisher</value>
      <webElementGuid>1fc908e1-70bb-4789-94b5-73f417f9fcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publisher&quot;)</value>
      <webElementGuid>db74e480-23c3-45b9-98d8-288c25ab5257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='publisher']</value>
      <webElementGuid>c8bd9aa2-880e-4340-9455-6a4669412657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>a16abcc4-e4b9-4059-b190-2ebac4030449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'publisher' and @name = 'publisher']</value>
      <webElementGuid>a81979b3-1c39-41ca-a101-117bb1faa866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
