<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promotional Price_promo</name>
   <tag></tag>
   <elementGuidId>b551adb1-121f-455a-9ada-2e93862a34c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e70a1d2-6df3-43f5-9345-84bce03a635a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a61cbcce-b9c2-4347-83e8-b496acf82c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>75e58d34-3531-499f-88da-c9fd372bee4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promo</value>
      <webElementGuid>ed2cb9b6-bed3-42a7-bba7-7a8912d807a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promo</value>
      <webElementGuid>9fbae9c1-a266-4a0e-a6f9-c34725a1796f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo&quot;)</value>
      <webElementGuid>d1484811-1cd9-42ec-9d4d-337ccaaac76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promo']</value>
      <webElementGuid>f8879596-0f61-4e76-aca8-74bb2a7230b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>8392d495-de90-4670-bb7a-04f378a0145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'promo' and @name = 'promo']</value>
      <webElementGuid>1300b8c4-84f9-4ca8-93f3-ff8aeb92d21e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
