<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_book_title</name>
   <tag></tag>
   <elementGuidId>e1cdbf38-2ef7-4ab5-9ab9-d0bcfff1ecb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#book_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='book_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bade490b-73fe-47c7-8a76-d2f74f2dcac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c502488-de28-495a-b23d-3f1f14f450bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>90cb9eaa-c037-455a-8063-5605f3f29841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>book_title</value>
      <webElementGuid>3d5a6289-242c-4174-bea1-7d4afa6eb1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>book_title</value>
      <webElementGuid>dd6b4bce-1266-4760-8c6a-fbc5f80b631a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book_title&quot;)</value>
      <webElementGuid>ffa8ed4d-38b5-4181-b44f-f09a9a77c487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='book_title']</value>
      <webElementGuid>16bc1b4f-ebdb-4bae-8529-c501d1e9159e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>2eb99e1c-a428-4c12-88c1-42f91a33add2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'book_title' and @name = 'book_title']</value>
      <webElementGuid>e694a522-fc45-4ba9-94ee-8596c721dd9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
