<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Language_language</name>
   <tag></tag>
   <elementGuidId>d4acbca6-46b0-4d01-9075-563383a59b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#language</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='language']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bd4398c-0ff0-4c00-b47b-b4e18e8a9d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9823e16-f61d-40c1-a1b3-1729e654134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f08229c1-06e6-4618-b6a6-8e64629f854d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language</value>
      <webElementGuid>117a0655-7310-47a6-873f-0ca037efcf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>language</value>
      <webElementGuid>77499e69-af0e-4c3d-aa91-98c0a09a70e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;language&quot;)</value>
      <webElementGuid>01c80cc3-51dd-4e29-8a19-2f2c44606350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='language']</value>
      <webElementGuid>d0d0c5cd-0593-4907-a07e-caaea0706c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>a00f23dc-ee7b-4a7a-917d-4b06c0b86c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'language' and @name = 'language']</value>
      <webElementGuid>485e7353-041c-4f8d-a561-f88fdf0314fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
